#!/bin/sh
# AUTHOR : R.Farid.Nugraha <farid_@msn.com>
# Errata update repository
# copy this file in /etc/cron.weekly or you can set in crontab
#
# Package module install
# yum install perl-Switch perl-Data-Dumper perl-Frontier-RPC perl-Text-Unidecode perl-XML-Simple pulp-admin-client pulp-rpm-admin-extensions -y


MAILTO=root

# try to create the lock and check the outcome
LOCKFILE=/var/run/errata.lock
#lockfile -r 0 ${LOCKFILE} 1>/dev/null 2>&1
#status=$?
#if [ ${status} -ne 0 ] ;then
if [ -e "$LOCKFILE" ]; then
        echo "Another instance already running. Aborting."
        exit 1
else
    	touch "$LOCKFILE"
fi
trap "rm ${LOCKFILE}" EXIT

#get errata file and checksums
cd /tmp
wget -N http://cefs.steve-meier.de/errata.latest.xml 1>/dev/null 2>&1
wget -N http://cefs.steve-meier.de/errata.latest.md5 1>/dev/null 2>&1
wget -N http://www.redhat.com/security/data/oval/com.redhat.rhsa-all.xml.bz2 1>/dev/null 2>&1
bunzip2 -f /tmp/com.redhat.rhsa-all.xml.bz2

#verify integrity
grep "errata.latest.xml$" errata.latest.md5 > myerrata.md5
md5sum -c myerrata.md5 1>/dev/null 2>&1

if [ "$?" == 0 ]; then
        #ok - import errata
        pulp-admin repo list --fields id | awk '/CentOS/ { print "--include-repo="$NF }' | xargs /sbin/errata_import.pl --errata=/tmp/errata.latest.xml --rhsa-oval=/tmp/com.redhat.rhsa-all.xml --quiet

        if [ "$?" != 0 ]; then
                echo "It seems like there was a problem while publishing the most recent errata..."
                exit 1
        fi
	rm /tmp/myerrata.md5
else
    	#errata information possibly invalid
        echo "ERROR: md5 checksum mismatch, check download!"
        exit 1
fi


